apiVersion: v1
kind: Service
metadata:
  name: {{ include "qapps.fullname" . }}
  labels:
    {{- include "qapps.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "qapps.fullname" . }}
