apiVersion: cert-manager.io/v1 
kind: ClusterIssuer
metadata:
  name: {{ include "qapps.fullname" . }}-issuer
  labels:
    {{- include "qapps.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.issuer.email }}
    server: {{ .Values.issuer.server }}
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - http01:
        ingress:
          class: nginx
