- name: "Prepare the join command from the master"
  hosts: denisova
  become: true
  tasks:
    - name: "Create join key and read output"
      command: microk8s add-node
      register: add_output

    - name: "Define the 'join_command' variable"
      set_fact:
        join_command: "{{ (add_output.stdout_lines | select('match', '.*192.168.0.*'))[0] }}"

    - name: "Debug: Printing the join command"
      debug:
        var: join_command

    - name: "Add K8S join command to a dummy host"
      add_host:
        name: "K8S_JOIN_HOLDER"
        command: "{{ join_command + ' ' }}"

- name: "Execute the join command in a worker node"
  hosts: ergaster
  become: true
  tasks:
    - name: "Debug: Printing the join command"
      debug:
        var: hostvars['K8S_JOIN_HOLDER']['command']

    - name: "Join the cluster from the generated join command"
      command: "{{ hostvars['K8S_JOIN_HOLDER']['command'] }}"