apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: musings-cert
  # cert-manager will put the resulting Secret in the same Kubernetes
  # namespace as the Certificate. You should create the certificate in
  # whichever namespace you want to configure a Host.
  namespace: default
spec:
  secretName: musings-cert
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  dnsNames:
  - musings.thruhere.net
  
