apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ceph-cert
  namespace: ceph
spec:
  secretName: ceph-cert
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  dnsNames:
  - ceph.southern.podzone.net
