apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: control-cert
  namespace: default
spec:
  secretName: control-cert
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  dnsNames:
  - control.southern.podzone.net
