apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      securityContext:
        fsGroup: 101
      volumes:
        - name: content-from-git
          persistentVolumeClaim:
            claimName: apache-volume-claim
      containers:
        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v4.0.0
          args:
            - --repo=https://github.com/MoTTTT/musings.git
            - --depth=1
            - --period=60s
            - --link=current
            - --root=/gitapache
          volumeMounts:
            - name: content-from-git
              mountPath: /gitapache
        - name: server
          image: httpd:alpine
          ports:
          - containerPort: 80
          volumeMounts:
            - name: content-from-git
              subPath: current/site
              mountPath: /usr/local/apache2/htdocs/
              readOnly: true


