# podzone-pc-nfs.yaml 
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.0.6
  share: /srv/nfs/k8s
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: apache-storage-class
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.0.6
  share: /srv/nfs/apachesites
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache-volume-claim
spec:
  storageClassName: apache-storage-class
  accessModes:
   - ReadWriteMany
  resources:
   requests:
    storage: 10Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: db-storage-class
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.0.6
  share: /srv/nfs/db
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volume-claim
spec:
  storageClassName: db-storage-class
  accessModes:
   - ReadWriteOnce
  resources:
   requests:
    storage: 10Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: backup-storage-class
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.0.6
  share: /srv/nfs/backup
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-volume-claim
spec:
  storageClassName: backup-storage-class
  accessModes:
   - ReadWriteMany
  resources:
   requests:
    storage: 10Gi