---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    app: apache
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      volumes:
      - name: doc-root-volume
        persistentVolumeClaim:
          claimName: apache-volume-claim
      containers:
      - name: apache
        image: ubuntu/apache2
        ports:
        - containerPort: 80
        volumeMounts: 
        - name: doc-root-volume
          mountPath: /var/www/html
