apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: podzone-ingress-class
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: k8s.io/ingress-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: podzone-ingress
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  ingressClassName: podzone-ingress-class
  tls:
  - hosts:
    - qsolutions.endoftheinternet.org
    secretName: qsolution-cert
  - hosts:
    - musings.thruhere.net
    secretName: musings-cert
  rules:
  - host: musings.thruhere.net
    http:
      paths:
      - backend:
         service:
           name: apache-service
           port:
             number: 80
        path: /
        pathType: Prefix
  - host: qsolutions.endoftheinternet.org
    http:
      paths:
      - backend:
         service:
           name: apache-service
           port:
             number: 80
        path: /
        pathType: Prefix
---
apiVersion: cert-manager.io/v1 
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    email: martinjcolley@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - http01:
        ingress:
          class: nginx
      selector: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: musings-cert
  # cert-manager will put the resulting Secret in the same Kubernetes
  # namespace as the Certificate. You should create the certificate in
  # whichever namespace you want to configure a Host.
  namespace: default
spec:
  secretName: musings-cert
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  dnsNames:
  - musings.thruhere.net
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qsolution-cert
  # cert-manager will put the resulting Secret in the same Kubernetes
  # namespace as the Certificate. You should create the certificate in
  # whichever namespace you want to configure a Host.
  namespace: default
spec:
  secretName: qsolution-cert
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  dnsNames:
  - qsolutions.endoftheinternet.org
 

