---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: apache-storage-class
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.0.6
  share: /srv/nfs/apachesites
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache-volume-claim
spec:
  storageClassName: apache-storage-class
  accessModes:
   - ReadWriteOnce
  resources:
   requests:
    storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    app: apache
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      volumes:
      - name: doc-root-volume
        persistentVolumeClaim:
          claimName: apache-volume-claim
      containers:
      - name: apache
        image: ubuntu/apache2
        ports:
        - containerPort: 80
        volumeMounts: 
        - name: doc-root-volume
          mountPath: /var/www/html
