apiVersion: cert-manager.io/v1 
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    email: martinjcolley@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - http01:
        ingress:
          class: nginx
      selector: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: musings-cert
  # cert-manager will put the resulting Secret in the same Kubernetes
  # namespace as the Certificate. You should create the certificate in
  # whichever namespace you want to configure a Host.
  namespace: default
spec:
  secretName: musings-cert
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  dnsNames:
  - musings.thruhere.net
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qsolution-cert
  # cert-manager will put the resulting Secret in the same Kubernetes
  # namespace as the Certificate. You should create the certificate in
  # whichever namespace you want to configure a Host.
  namespace: default
spec:
  secretName: qsolution-cert
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  dnsNames:
  - qsolutions.endoftheinternet.org
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: control-cert
  # cert-manager will put the resulting Secret in the same Kubernetes
  # namespace as the Certificate. You should create the certificate in
  # whichever namespace you want to configure a Host.
  namespace: default
spec:
  secretName: control-cert
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  dnsNames:
  - control.southern.podzone.net
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dashboard-cert
  # cert-manager will put the resulting Secret in the same Kubernetes
  # namespace as the Certificate. You should create the certificate in
  # whichever namespace you want to configure a Host.
  namespace: kube-system
spec:
  secretName: dashboard-cert
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  dnsNames:
  - dashboard.southern.podzone.net
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-cert
  # cert-manager will put the resulting Secret in the same Kubernetes
  # namespace as the Certificate. You should create the certificate in
  # whichever namespace you want to configure a Host.
  namespace: kube-system
spec:
  secretName: opensearch-cert
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  dnsNames:
  - opensearch.southern.podzone.net
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana-cert
  # cert-manager will put the resulting Secret in the same Kubernetes
  # namespace as the Certificate. You should create the certificate in
  # whichever namespace you want to configure a Host.
  namespace: kube-system
spec:
  secretName: kibana-cert
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  dnsNames:
  - kibana.southern.podzone.net

